theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dirt" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
locale: "en-US"
title: About me
name: "Tuan Anh NGUYEN"
description: "Master Data Science and Artificial Intelligence"
masthead_title: "About me - Tuan Anh Nguyen"
author: Tuan Anh Nguyen
